#ifndef __KEYSYMS_H_INCLUDED__
#	define __KEYSYMS_H_INCLUDED__

//!!!TODO Make enum

class KeySyms
{
public:
	enum
	{
		KeyUnknown     = -1,
		KeySpace       = 32,
		KeySpecial     = 256,
		KeyESC         = KeySpecial+1,
		KeyF1          = KeySpecial+2,
		KeyF2          = KeySpecial+3,
		KeyF3          = KeySpecial+4,
		KeyF4          = KeySpecial+5,
		KeyF5          = KeySpecial+6,
		KeyF6          = KeySpecial+7,
		KeyF7          = KeySpecial+8,
		KeyF8          = KeySpecial+9,
		KeyF9          = KeySpecial+10,
		KeyF10         = KeySpecial+11,
		KeyF11         = KeySpecial+12,
		KeyF12         = KeySpecial+13,
		KeyF13         = KeySpecial+14,
		KeyF14         = KeySpecial+15,
		KeyF15         = KeySpecial+16,
		KeyF16         = KeySpecial+17,
		KeyF17         = KeySpecial+18,
		KeyF18         = KeySpecial+19,
		KeyF19         = KeySpecial+20,
		KeyF20         = KeySpecial+21,
		KeyF21         = KeySpecial+22,
		KeyF22         = KeySpecial+23,
		KeyF23         = KeySpecial+24,
		KeyF24         = KeySpecial+25,
		KeyF25         = KeySpecial+26,
		KeyUp          = KeySpecial+27,
		KeyDown        = KeySpecial+28,
		KeyLeft        = KeySpecial+29,
		KeyRight       = KeySpecial+30,
		KeyLShift      = KeySpecial+31,
		KeyRShift      = KeySpecial+32,
		KeyLCtrl       = KeySpecial+33,
		KeyRCtrl       = KeySpecial+34,
		KeyLAlt        = KeySpecial+35,
		KeyRAlt        = KeySpecial+36,
		KeyTab         = KeySpecial+37,
		KeyEnter       = KeySpecial+38,
		KeyBackspace   = KeySpecial+39,
		KeyInsert      = KeySpecial+40,
		KeyDel         = KeySpecial+41,
		KeyPageup      = KeySpecial+42,
		KeyPagedown    = KeySpecial+43,
		KeyHome        = KeySpecial+44,
		KeyEnd         = KeySpecial+45,
		KeyKP0         = KeySpecial+46,
		KeyKP1         = KeySpecial+47,
		KeyKP2         = KeySpecial+48,
		KeyKP3         = KeySpecial+49,
		KeyKP4         = KeySpecial+50,
		KeyKP5         = KeySpecial+51,
		KeyKP6         = KeySpecial+52,
		KeyKP7         = KeySpecial+53,
		KeyKP8         = KeySpecial+54,
		KeyKP9         = KeySpecial+55,
		KeyKPDivide    = KeySpecial+56,
		KeyKPMultiply  = KeySpecial+57,
		KeyKPSubtract  = KeySpecial+58,
		KeyKPAdd       = KeySpecial+59,
		KeyKPDecimal   = KeySpecial+60,
		KeyKPEqual     = KeySpecial+61,
		KeyKPEnter     = KeySpecial+62,
		KeyCount       = KeyKPEnter+1
	};
};

#endif