/* Generated by re2c 0.13.6 on Sat Nov 09 13:49:31 2013 */
#include <assert.h>
#include <memory.h>
#include <stdio.h>
#include <string.h>

#include "mjson.h"

enum mjson_token_t
{
    TOK_NONE,
    TOK_IDENTIFIER,
    TOK_NOESC_STRING,
    TOK_STRING,
    TOK_OCT_NUMBER,
    TOK_HEX_NUMBER,
    TOK_DEC_NUMBER,
    TOK_FLOAT_NUMBER,
    TOK_COMMA,
    TOK_COLON,
    TOK_EQUAL,
    TOK_LEFT_BRACKET,
    TOK_RIGHT_BRACKET,
    TOK_LEFT_CURLY_BRACKET,
    TOK_RIGHT_CURLY_BRACKET,
    TOK_FALSE,
    TOK_TRUE,
    TOK_NULL,
    TOK_WHITESPACE,
    TOK_INVALID,
    TOK_COUNT
};

struct _mjson_parser_t
{
    int token;
    uint8_t* start;
    uint8_t* next;
    uint8_t* end;
    uint8_t* bjson;
    uint8_t* bjson_limit;
};

struct _mjson_entry_t
{
    uint32_t  id;
    union
    {
        uint32_t val_u32;
        int32_t  val_s32;
        float    val_f32;
    };
};

#define RETURN_VAL_IF_FAIL(cond, val) if (!(cond)) return (val)
#define RETURN_IF_FAIL(cond) if (!(cond)) return
#define MAX_UTF8_CHAR_LEN 6
#define TRUE  1
#define FALSE 0

typedef struct _mjson_parser_t  mjson_parser_t;
typedef struct _mjson_entry_t   mjson_entry_t;

static void* parsectx_allocate_output(mjson_parser_t* ctx, ptrdiff_t size);

static void parsectx_next_token    (mjson_parser_t* context);

static int parse_value_list    (mjson_parser_t *context);
static int parse_key_value_pair(mjson_parser_t *context, int stop_token);

static mjson_element_t next_element(mjson_element_t element);

int mjson_parse(const char *json_data, size_t json_data_size, void* storage_buf, size_t storage_buf_size, const mjson_entry_t** top_element)
{
    uint32_t* fourcc;
    mjson_parser_t c = {
        TOK_NONE, 0,
        (uint8_t*)json_data,   (uint8_t*)json_data + json_data_size,
        (uint8_t*)storage_buf, (uint8_t*)storage_buf + storage_buf_size
    };
    int stop_token = TOK_NONE;

    *top_element = 0;

    fourcc = (uint32_t*)parsectx_allocate_output(&c, (ptrdiff_t)sizeof(uint32_t));

    if (!fourcc) return 0;

    *fourcc = '23JB';

    parsectx_next_token(&c);

    if (c.token == TOK_LEFT_BRACKET)
    {
        parsectx_next_token(&c);
        if (!parse_value_list(&c))
            return 0;
    }
    else
    {
        if (c.token == TOK_LEFT_CURLY_BRACKET)
        {
            stop_token = TOK_RIGHT_CURLY_BRACKET;
            parsectx_next_token(&c);
        }

        if (!parse_key_value_pair(&c, stop_token))
            return 0;
    }

    if (c.token != TOK_NONE)
        return 0;

    *top_element = (mjson_entry_t*)(fourcc + 1);

    return 1;
}

mjson_element_t mjson_get_top_element(void* storage_buf, size_t storage_buf_size)
{
    mjson_element_t top = (mjson_element_t)storage_buf;
    
    RETURN_VAL_IF_FAIL(top, NULL);
    RETURN_VAL_IF_FAIL(top->id == MJSON_ID_DICT32 || top->id == MJSON_ID_ARRAY32, NULL);
    RETURN_VAL_IF_FAIL(top->val_u32 <= storage_buf_size, NULL);
    
    return top;
}

mjson_element_t mjson_get_element_first(mjson_element_t array)
{
    RETURN_VAL_IF_FAIL(array, NULL);
    RETURN_VAL_IF_FAIL(array->id == MJSON_ID_ARRAY32, NULL);
    
    return array + 1;
}

mjson_element_t mjson_get_element_next(mjson_element_t array, mjson_element_t current_value)
{
    mjson_element_t next = NULL;

    RETURN_VAL_IF_FAIL(array, NULL);
    RETURN_VAL_IF_FAIL(current_value, NULL);
    RETURN_VAL_IF_FAIL(array->id == MJSON_ID_ARRAY32, NULL);
    RETURN_VAL_IF_FAIL((uint8_t*)array + array->val_u32 > (uint8_t*)current_value, NULL);
    
    next = next_element(current_value);
    
    RETURN_VAL_IF_FAIL((uint8_t*)array + array->val_u32 > (uint8_t*)next, NULL);
    
    return next;
}

mjson_element_t mjson_get_element(mjson_element_t array, int index)
{
    mjson_element_t result;
    
    result = mjson_get_element_first(array);
    while (result && index--)
        result = mjson_get_element_next(array, result);
    
    return result;
}

mjson_element_t mjson_get_member_first(mjson_element_t dictionary, mjson_element_t* value)
{
    RETURN_VAL_IF_FAIL(dictionary, NULL);
    RETURN_VAL_IF_FAIL(dictionary->id == MJSON_ID_DICT32, NULL);
    RETURN_VAL_IF_FAIL((dictionary+1)->id == MJSON_ID_UTF8_KEY32, NULL);
    
    *value = next_element(dictionary+1);
    
    return dictionary + 1;
}

mjson_element_t mjson_get_member_next(mjson_element_t dictionary, mjson_element_t current_key, mjson_element_t* next_value)
{
    mjson_element_t next_key = NULL;

    RETURN_VAL_IF_FAIL(dictionary, NULL);
    RETURN_VAL_IF_FAIL(dictionary->id == MJSON_ID_DICT32, NULL);
    RETURN_VAL_IF_FAIL(current_key, NULL);
    RETURN_VAL_IF_FAIL((uint8_t*)dictionary + dictionary->val_u32 > (uint8_t*)current_key, NULL);
    RETURN_VAL_IF_FAIL(current_key->id == MJSON_ID_UTF8_KEY32, NULL);
    
    next_key = next_element(current_key);
    next_key = next_element(next_key);
    
    RETURN_VAL_IF_FAIL(next_key, NULL);
    RETURN_VAL_IF_FAIL((uint8_t*)dictionary + dictionary->val_u32 > (uint8_t*)next_key, NULL);
    RETURN_VAL_IF_FAIL(next_key->id == MJSON_ID_UTF8_KEY32, NULL);

    *next_value = next_element(next_key);
   
    return next_key;    
}

mjson_element_t mjson_get_member(mjson_element_t dictionary, const char* name)
{
    mjson_element_t key, result;
    
    key = mjson_get_member_first(dictionary, &result);
    while (key && strncmp(name, (char*)(key+1), key->val_u32) != 0)
        result = mjson_get_member_next(dictionary, key, &result);
    
    return result;
}

int mjson_get_type(mjson_element_t element)
{
    RETURN_VAL_IF_FAIL(element, MJSON_ID_NULL);
    
    return element->id;
}

const char* mjson_get_string(mjson_element_t element, const char* fallback)
{
    RETURN_VAL_IF_FAIL(element, fallback);
    RETURN_VAL_IF_FAIL(element->id == MJSON_ID_UTF8_STRING32 ||
                       element->id == MJSON_ID_UTF8_KEY32,
                       fallback);
    
    return (const char*)(element+1);
}

int32_t mjson_get_int(mjson_element_t element, int32_t fallback)
{
    RETURN_VAL_IF_FAIL(element, fallback);
    RETURN_VAL_IF_FAIL(element->id == MJSON_ID_SINT32, fallback);
    
    return element->val_s32;
}

float mjson_get_float(mjson_element_t element, float fallback)
{
    RETURN_VAL_IF_FAIL(element, fallback);
    RETURN_VAL_IF_FAIL(element->id == MJSON_ID_FLOAT32, fallback);
    
    return element->val_f32;
}

int mjson_get_bool(mjson_element_t element, int fallback)
{
    RETURN_VAL_IF_FAIL(element, fallback);
    RETURN_VAL_IF_FAIL(element->id == MJSON_ID_TRUE || element->id == MJSON_ID_FALSE, fallback);
    
    return element->id == MJSON_ID_TRUE;
}

int mjson_is_null(mjson_element_t element)
{
    RETURN_VAL_IF_FAIL(element, TRUE);

    return element->id == MJSON_ID_NULL;
}

/////////////////////////////////////////////////////////////////////////////
// API helpers
/////////////////////////////////////////////////////////////////////////////

static size_t element_size(mjson_element_t element)
{
    RETURN_VAL_IF_FAIL(element, 0);

    switch(element->id)
    {
        case MJSON_ID_NULL:
        case MJSON_ID_FALSE:
        case MJSON_ID_EMPTY_STRING:
        case MJSON_ID_TRUE:
            return sizeof(uint32_t);

        case MJSON_ID_UINT32:
        case MJSON_ID_SINT32:
        case MJSON_ID_FLOAT32:
            return sizeof(mjson_entry_t);

        case MJSON_ID_UTF8_KEY32:
        case MJSON_ID_UTF8_STRING32:
            return sizeof(mjson_entry_t) + ((element->val_u32 + 1 + 3) & (~3));

        case MJSON_ID_BINARY32:
        case MJSON_ID_ARRAY32:
        case MJSON_ID_DICT32:
            return sizeof(mjson_entry_t) + ((element->val_u32 + 3) & (~3));
    };

    return 0;
}

static mjson_element_t next_element(mjson_element_t element)
{
    size_t size;
    
    RETURN_VAL_IF_FAIL(element, 0);

    size = element_size(element);
    assert(size>0);
    
    return (mjson_element_t)((uint8_t*)element + size);
}

static void* parsectx_reserve_output(mjson_parser_t* ctx, ptrdiff_t size)
{
    return (ctx->bjson_limit - ctx->bjson < size) ? 0 : ctx->bjson;
}

static void parsectx_advance_output(mjson_parser_t* ctx, ptrdiff_t size)
{
    ctx->bjson += size;
}

static void* parsectx_allocate_output(mjson_parser_t* ctx, ptrdiff_t size)
{
    void* ptr;

    if (ctx->bjson_limit - ctx->bjson < size)
        return 0;

    ptr = ctx->bjson;
    ctx->bjson += size;

    return ptr;
}

//TODO: what about 64 bit code????
static void parsectx_align4_output(mjson_parser_t* ctx)
{
    ctx->bjson = (uint8_t*)(((ptrdiff_t)ctx->bjson + 3) & (~3));
}

static void unicode_cp_to_utf8(uint32_t uni_cp, uint8_t* utf8char/*[6]*/, size_t* charlen)
{
    uint32_t first, i;
    
    if (uni_cp < 0x80)
    {
        first   = 0;
        *charlen = 1;
    }
    else if (uni_cp < 0x800)
    {
        first   = 0xc0;
        *charlen = 2;
    }
    else if (uni_cp < 0x10000)
    {
        first   = 0xe0;
        *charlen = 3;
    }
    else if (uni_cp < 0x200000)
    {
        first   = 0xf0;
        *charlen = 4;
    }
    else if (uni_cp < 0x4000000)
    {
        first   = 0xf8;
        *charlen = 5;
    }
    else
    {
        first   = 0xfc;
        *charlen = 6;
    }

    for (i = *charlen - 1; i > 0; --i)
    {
        utf8char[i] = (uni_cp & 0x3f) | 0x80;
        uni_cp >>= 6;
    }
    utf8char[0] = uni_cp | first;
}

/////////////////////////////////////////////////////////////////////////////
// Lexer+Parser code
/////////////////////////////////////////////////////////////////////////////



static void parsectx_next_token(mjson_parser_t* context)
{
#define YYREADINPUT(c) (c>=e?0:*c)
#define YYCTYPE        uint8_t
#define YYCURSOR       c
#define YYMARKER       m

    uint8_t* c = context->next;
    uint8_t* e = context->end;
    uint8_t* m = NULL;
    uint8_t* s;
    int token = TOK_NONE;

    assert(context);
    RETURN_IF_FAIL(context->next != NULL);

    while (TRUE)
    {
        s = c;


        {
            YYCTYPE yych;
            unsigned int yyaccept = 0;

            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '<') {
                if (yych <= '"') {
                    if (yych <= '\f') {
                        if (yych <= 0x00) goto yy31;
                        if (yych <= 0x08) goto yy33;
                        if (yych >= '\v') goto yy33;
                    } else {
                        if (yych <= 0x1F) {
                            if (yych >= 0x0E) goto yy33;
                        } else {
                            if (yych <= ' ') goto yy2;
                            if (yych <= '!') goto yy33;
                            goto yy30;
                        }
                    }
                } else {
                    if (yych <= '.') {
                        if (yych <= '+') {
                            if (yych <= '*') goto yy33;
                            goto yy22;
                        } else {
                            if (yych <= ',') goto yy18;
                            if (yych <= '-') goto yy22;
                            goto yy24;
                        }
                    } else {
                        if (yych <= '0') {
                            if (yych <= '/') goto yy4;
                            goto yy20;
                        } else {
                            if (yych <= '9') goto yy23;
                            if (yych <= ':') goto yy14;
                            goto yy33;
                        }
                    }
                }
            } else {
                if (yych <= 'e') {
                    if (yych <= '\\') {
                        if (yych <= '@') {
                            if (yych <= '=') goto yy16;
                            goto yy33;
                        } else {
                            if (yych <= 'Z') goto yy29;
                            if (yych <= '[') goto yy10;
                            goto yy33;
                        }
                    } else {
                        if (yych <= '^') {
                            if (yych <= ']') goto yy12;
                            goto yy33;
                        } else {
                            if (yych == '`') goto yy33;
                            goto yy29;
                        }
                    }
                } else {
                    if (yych <= 't') {
                        if (yych <= 'm') {
                            if (yych <= 'f') goto yy27;
                            goto yy29;
                        } else {
                            if (yych <= 'n') goto yy28;
                            if (yych <= 's') goto yy29;
                            goto yy25;
                        }
                    } else {
                        if (yych <= '{') {
                            if (yych <= 'z') goto yy29;
                            goto yy6;
                        } else {
                            if (yych == '}') goto yy8;
                            goto yy33;
                        }
                    }
                }
            }
yy2:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            goto yy126;
yy3:
            {
                continue; 
            }
yy4:
            yyaccept = 0;
            ++YYCURSOR;
            YYMARKER = YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych == '*') goto yy108;
            if (yych == '/') goto yy110;
yy5:
            {
                context->token = TOK_INVALID;
                return;
            }
yy6:
            ++YYCURSOR;
            {
                token = TOK_LEFT_CURLY_BRACKET;
                goto done;
            }
yy8:
            ++YYCURSOR;
            {
                token = TOK_RIGHT_CURLY_BRACKET;
                goto done;
            }
yy10:
            ++YYCURSOR;
            {
                token = TOK_LEFT_BRACKET;
                goto done;
            }
yy12:
            ++YYCURSOR;
            {
                token = TOK_RIGHT_BRACKET;
                goto done;
            }
yy14:
            ++YYCURSOR;
            {
                token = TOK_COLON;
                goto done;
            }
yy16:
            ++YYCURSOR;
            {
                token = TOK_EQUAL;
                goto done;
            }
yy18:
            ++YYCURSOR;
            {
                token = TOK_COMMA;
                goto done;
            }
yy20:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= 'X') {
                if (yych <= '/') {
                    if (yych == '.') goto yy100;
                } else {
                    if (yych <= '9') goto yy100;
                    if (yych <= '@') goto yy21;
                    if (yych <= 'W') goto yy100;
                    goto yy104;
                }
            } else {
                if (yych <= '`') {
                    if (yych <= 'Z') goto yy100;
                    if (yych == '_') goto yy100;
                } else {
                    if (yych == 'x') goto yy104;
                    if (yych <= 'z') goto yy100;
                }
            }
yy21:
            {
                token = TOK_DEC_NUMBER;
                goto done;
            }
yy22:
            yyaccept = 0;
            ++YYCURSOR;
            YYMARKER = YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '/') {
                if (yych == '.') goto yy95;
                goto yy5;
            } else {
                if (yych <= '0') goto yy92;
                if (yych <= '9') goto yy93;
                goto yy5;
            }
yy23:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            goto yy71;
yy24:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '/') goto yy5;
            if (yych <= '9') goto yy63;
            goto yy5;
yy25:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych == 'r') goto yy59;
            goto yy49;
yy26:
            {
                token = TOK_IDENTIFIER;
                goto done;
            }
yy27:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych == 'a') goto yy54;
            goto yy49;
yy28:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych == 'u') goto yy50;
            goto yy49;
yy29:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            goto yy49;
yy30:
            yyaccept = 0;
            ++YYCURSOR;
            YYMARKER = YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= 0x00) goto yy5;
            goto yy35;
yy31:
            ++YYCURSOR;
            { 
                context->token = TOK_NONE;
                return;
            }
yy33:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            goto yy5;
yy34:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
yy35:
            if (yych <= '"') {
                if (yych <= 0x00) goto yy36;
                if (yych <= '!') goto yy34;
                goto yy38;
            } else {
                if (yych == '\\') goto yy37;
                goto yy34;
            }
yy36:
            YYCURSOR = YYMARKER;
            if (yyaccept <= 2) {
                if (yyaccept <= 1) {
                    if (yyaccept == 0) {
                        goto yy5;
                    } else {
                        goto yy65;
                    }
                } else {
                    goto yy74;
                }
            } else {
                if (yyaccept == 3) {
                    goto yy21;
                } else {
                    goto yy120;
                }
            }
yy37:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= 'e') {
                if (yych <= '/') {
                    if (yych == '"') goto yy41;
                    if (yych <= '.') goto yy36;
                    goto yy41;
                } else {
                    if (yych <= '\\') {
                        if (yych <= '[') goto yy36;
                        goto yy41;
                    } else {
                        if (yych == 'b') goto yy41;
                        goto yy36;
                    }
                }
            } else {
                if (yych <= 'q') {
                    if (yych <= 'f') goto yy41;
                    if (yych == 'n') goto yy41;
                    goto yy36;
                } else {
                    if (yych <= 's') {
                        if (yych <= 'r') goto yy41;
                        goto yy36;
                    } else {
                        if (yych <= 't') goto yy41;
                        if (yych <= 'u') goto yy40;
                        goto yy36;
                    }
                }
            }
yy38:
            ++YYCURSOR;
            {
                token = TOK_NOESC_STRING;
                goto done;
            }
yy40:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '@') {
                if (yych <= '/') goto yy36;
                if (yych <= '9') goto yy45;
                goto yy36;
            } else {
                if (yych <= 'F') goto yy45;
                if (yych <= '`') goto yy36;
                if (yych <= 'f') goto yy45;
                goto yy36;
            }
yy41:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '"') {
                if (yych <= 0x00) goto yy36;
                if (yych <= '!') goto yy41;
            } else {
                if (yych == '\\') goto yy37;
                goto yy41;
            }
            ++YYCURSOR;
            {
                token = TOK_STRING;
                goto done;
            }
yy45:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '@') {
                if (yych <= '/') goto yy36;
                if (yych >= ':') goto yy36;
            } else {
                if (yych <= 'F') goto yy46;
                if (yych <= '`') goto yy36;
                if (yych >= 'g') goto yy36;
            }
yy46:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '@') {
                if (yych <= '/') goto yy36;
                if (yych >= ':') goto yy36;
            } else {
                if (yych <= 'F') goto yy47;
                if (yych <= '`') goto yy36;
                if (yych >= 'g') goto yy36;
            }
yy47:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '@') {
                if (yych <= '/') goto yy36;
                if (yych <= '9') goto yy41;
                goto yy36;
            } else {
                if (yych <= 'F') goto yy41;
                if (yych <= '`') goto yy36;
                if (yych <= 'f') goto yy41;
                goto yy36;
            }
yy48:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
yy49:
            if (yych <= 'Z') {
                if (yych <= '/') goto yy26;
                if (yych <= '9') goto yy48;
                if (yych <= '@') goto yy26;
                goto yy48;
            } else {
                if (yych <= '_') {
                    if (yych <= '^') goto yy26;
                    goto yy48;
                } else {
                    if (yych <= '`') goto yy26;
                    if (yych <= 'z') goto yy48;
                    goto yy26;
                }
            }
yy50:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych != 'l') goto yy49;
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych != 'l') goto yy49;
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= 'Z') {
                if (yych <= '/') goto yy53;
                if (yych <= '9') goto yy48;
                if (yych >= 'A') goto yy48;
            } else {
                if (yych <= '_') {
                    if (yych >= '_') goto yy48;
                } else {
                    if (yych <= '`') goto yy53;
                    if (yych <= 'z') goto yy48;
                }
            }
yy53:
            {
                token = TOK_NULL;
                goto done;
            }
yy54:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych != 'l') goto yy49;
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych != 's') goto yy49;
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych != 'e') goto yy49;
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= 'Z') {
                if (yych <= '/') goto yy58;
                if (yych <= '9') goto yy48;
                if (yych >= 'A') goto yy48;
            } else {
                if (yych <= '_') {
                    if (yych >= '_') goto yy48;
                } else {
                    if (yych <= '`') goto yy58;
                    if (yych <= 'z') goto yy48;
                }
            }
yy58:
            {
                token = TOK_FALSE;
                goto done;
            }
yy59:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych != 'u') goto yy49;
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych != 'e') goto yy49;
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= 'Z') {
                if (yych <= '/') goto yy62;
                if (yych <= '9') goto yy48;
                if (yych >= 'A') goto yy48;
            } else {
                if (yych <= '_') {
                    if (yych >= '_') goto yy48;
                } else {
                    if (yych <= '`') goto yy62;
                    if (yych <= 'z') goto yy48;
                }
            }
yy62:
            {
                token = TOK_TRUE;
                goto done;
            }
yy63:
            yyaccept = 1;
            ++YYCURSOR;
            YYMARKER = YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= 'D') {
                if (yych <= '/') goto yy65;
                if (yych <= '9') goto yy63;
            } else {
                if (yych <= 'E') goto yy66;
                if (yych == 'e') goto yy66;
            }
yy65:
            {
                token = TOK_FLOAT_NUMBER;
                goto done;
            }
yy66:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= ',') {
                if (yych != '+') goto yy36;
            } else {
                if (yych <= '-') goto yy67;
                if (yych <= '/') goto yy36;
                if (yych <= '9') goto yy68;
                goto yy36;
            }
yy67:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '/') goto yy36;
            if (yych >= ':') goto yy36;
yy68:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '/') goto yy65;
            if (yych <= '9') goto yy68;
            goto yy65;
yy70:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
yy71:
            if (yych <= 'E') {
                if (yych <= '/') {
                    if (yych == '.') goto yy76;
                    goto yy21;
                } else {
                    if (yych <= '9') goto yy70;
                    if (yych <= '@') goto yy21;
                    if (yych >= 'E') goto yy75;
                }
            } else {
                if (yych <= '`') {
                    if (yych <= 'Z') goto yy72;
                    if (yych != '_') goto yy21;
                } else {
                    if (yych == 'e') goto yy75;
                    if (yych >= '{') goto yy21;
                }
            }
yy72:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= 'Z') {
                if (yych <= '/') goto yy74;
                if (yych <= '9') goto yy72;
                if (yych >= 'A') goto yy72;
            } else {
                if (yych <= '_') {
                    if (yych >= '_') goto yy72;
                } else {
                    if (yych <= '`') goto yy74;
                    if (yych <= 'z') goto yy72;
                }
            }
yy74:
            {
                context->token = TOK_INVALID;
                return;
            }
yy75:
            yyaccept = 2;
            ++YYCURSOR;
            YYMARKER = YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '9') {
                if (yych <= ',') {
                    if (yych == '+') goto yy87;
                    goto yy74;
                } else {
                    if (yych <= '-') goto yy87;
                    if (yych <= '/') goto yy74;
                    goto yy88;
                }
            } else {
                if (yych <= '^') {
                    if (yych <= '@') goto yy74;
                    if (yych <= 'Z') goto yy72;
                    goto yy74;
                } else {
                    if (yych == '`') goto yy74;
                    if (yych <= 'z') goto yy72;
                    goto yy74;
                }
            }
yy76:
            yyaccept = 1;
            ++YYCURSOR;
            YYMARKER = YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych == 'E') goto yy79;
            if (yych == 'e') goto yy79;
            goto yy78;
yy77:
            yyaccept = 1;
            ++YYCURSOR;
            YYMARKER = YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
yy78:
            if (yych <= 'D') {
                if (yych <= '/') goto yy65;
                if (yych <= '9') goto yy77;
                goto yy65;
            } else {
                if (yych <= 'E') goto yy83;
                if (yych == 'e') goto yy83;
                goto yy65;
            }
yy79:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= ',') {
                if (yych != '+') goto yy36;
            } else {
                if (yych <= '-') goto yy80;
                if (yych <= '/') goto yy36;
                if (yych <= '9') goto yy81;
                goto yy36;
            }
yy80:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '/') goto yy36;
            if (yych >= ':') goto yy36;
yy81:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '/') goto yy65;
            if (yych <= '9') goto yy81;
            goto yy65;
yy83:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= ',') {
                if (yych != '+') goto yy36;
            } else {
                if (yych <= '-') goto yy84;
                if (yych <= '/') goto yy36;
                if (yych <= '9') goto yy85;
                goto yy36;
            }
yy84:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '/') goto yy36;
            if (yych >= ':') goto yy36;
yy85:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '/') goto yy65;
            if (yych <= '9') goto yy85;
            goto yy65;
yy87:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '/') goto yy36;
            if (yych <= '9') goto yy90;
            goto yy36;
yy88:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= 'Z') {
                if (yych <= '/') goto yy65;
                if (yych <= '9') goto yy88;
                if (yych <= '@') goto yy65;
                goto yy72;
            } else {
                if (yych <= '_') {
                    if (yych <= '^') goto yy65;
                    goto yy72;
                } else {
                    if (yych <= '`') goto yy65;
                    if (yych <= 'z') goto yy72;
                    goto yy65;
                }
            }
yy90:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '/') goto yy65;
            if (yych <= '9') goto yy90;
            goto yy65;
yy92:
            yyaccept = 3;
            ++YYCURSOR;
            YYMARKER = YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '9') {
                if (yych == '.') goto yy76;
                if (yych <= '/') goto yy21;
                goto yy97;
            } else {
                if (yych <= 'E') {
                    if (yych <= 'D') goto yy21;
                    goto yy96;
                } else {
                    if (yych == 'e') goto yy96;
                    goto yy21;
                }
            }
yy93:
            yyaccept = 3;
            ++YYCURSOR;
            YYMARKER = YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '9') {
                if (yych == '.') goto yy76;
                if (yych <= '/') goto yy21;
                goto yy93;
            } else {
                if (yych <= 'E') {
                    if (yych <= 'D') goto yy21;
                    goto yy96;
                } else {
                    if (yych == 'e') goto yy96;
                    goto yy21;
                }
            }
yy95:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '/') goto yy36;
            if (yych <= '9') goto yy63;
            goto yy36;
yy96:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= ',') {
                if (yych == '+') goto yy87;
                goto yy36;
            } else {
                if (yych <= '-') goto yy87;
                if (yych <= '/') goto yy36;
                if (yych <= '9') goto yy90;
                goto yy36;
            }
yy97:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '9') {
                if (yych == '.') goto yy76;
                if (yych <= '/') goto yy36;
                goto yy97;
            } else {
                if (yych <= 'E') {
                    if (yych <= 'D') goto yy36;
                    goto yy96;
                } else {
                    if (yych == 'e') goto yy96;
                    goto yy36;
                }
            }
yy99:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
yy100:
            if (yych <= 'E') {
                if (yych <= '7') {
                    if (yych == '.') goto yy76;
                    if (yych >= '0') goto yy99;
                } else {
                    if (yych <= '9') goto yy102;
                    if (yych <= '@') goto yy101;
                    if (yych <= 'D') goto yy72;
                    goto yy75;
                }
            } else {
                if (yych <= '`') {
                    if (yych <= 'Z') goto yy72;
                    if (yych == '_') goto yy72;
                } else {
                    if (yych == 'e') goto yy75;
                    if (yych <= 'z') goto yy72;
                }
            }
yy101:
            {
                token = TOK_OCT_NUMBER;
                goto done;
            }
yy102:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= 'E') {
                if (yych <= '/') {
                    if (yych == '.') goto yy76;
                    goto yy74;
                } else {
                    if (yych <= '9') goto yy102;
                    if (yych <= '@') goto yy74;
                    if (yych <= 'D') goto yy72;
                    goto yy75;
                }
            } else {
                if (yych <= '`') {
                    if (yych <= 'Z') goto yy72;
                    if (yych == '_') goto yy72;
                    goto yy74;
                } else {
                    if (yych == 'e') goto yy75;
                    if (yych <= 'z') goto yy72;
                    goto yy74;
                }
            }
yy104:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= 'Z') {
                if (yych <= '/') goto yy74;
                if (yych <= '9') goto yy106;
                if (yych <= '@') goto yy74;
                goto yy106;
            } else {
                if (yych <= '_') {
                    if (yych <= '^') goto yy74;
                    goto yy106;
                } else {
                    if (yych <= '`') goto yy74;
                    if (yych <= 'z') goto yy106;
                    goto yy74;
                }
            }
yy105:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
yy106:
            if (yych <= 'Z') {
                if (yych <= '9') {
                    if (yych >= '0') goto yy105;
                } else {
                    if (yych <= '@') goto yy107;
                    if (yych <= 'F') goto yy105;
                    goto yy72;
                }
            } else {
                if (yych <= '`') {
                    if (yych == '_') goto yy72;
                } else {
                    if (yych <= 'f') goto yy105;
                    if (yych <= 'z') goto yy72;
                }
            }
yy107:
            {
                token = TOK_HEX_NUMBER;
                goto done;
            }
yy108:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= 0x00) goto yy36;
            if (yych == '*') goto yy114;
            goto yy108;
yy110:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= 0x00) goto yy36;
            if (yych != '\n') goto yy110;
            ++YYCURSOR;
            {
                continue; 
            }
yy114:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych == '*') goto yy117;
            if (yych == '/') goto yy119;
            goto yy116;
yy115:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
yy116:
            if (yych <= 0x00) goto yy36;
            if (yych == '*') goto yy122;
            goto yy115;
yy117:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '*') {
                if (yych <= 0x00) goto yy36;
                if (yych <= ')') goto yy115;
                goto yy117;
            } else {
                if (yych == '/') goto yy121;
                goto yy115;
            }
yy119:
            ++YYCURSOR;
yy120:
            {
                continue; 
            }
yy121:
            yyaccept = 4;
            ++YYCURSOR;
            YYMARKER = YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= 0x00) goto yy120;
            if (yych != '*') goto yy115;
yy122:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '*') {
                if (yych <= 0x00) goto yy36;
                if (yych <= ')') goto yy115;
            } else {
                if (yych == '/') goto yy119;
                goto yy115;
            }
yy123:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '*') {
                if (yych <= 0x00) goto yy36;
                if (yych <= ')') goto yy115;
                goto yy123;
            } else {
                if (yych == '/') goto yy121;
                goto yy115;
            }
yy125:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
yy126:
            if (yych <= '\f') {
                if (yych <= 0x08) goto yy3;
                if (yych <= '\n') goto yy125;
                goto yy3;
            } else {
                if (yych <= '\r') goto yy125;
                if (yych == ' ') goto yy125;
                goto yy3;
            }
        }

    }

done:
    context->token = token;
    context->start = s;
    context->next  = c;

#undef YYREADINPUT
#undef YYCTYPE           
#undef YYCURSOR          
#undef YYMARKER          
}

static int parse_number(mjson_parser_t *context)
{
    int            num_parsed;
    uint8_t        bjson_id;
    const char*    format;
    mjson_entry_t* bdata;

    switch(context->token)
    {
        case TOK_OCT_NUMBER:
            bjson_id = MJSON_ID_SINT32;
            format   = "%o";
            break;
        case TOK_HEX_NUMBER:
            bjson_id = MJSON_ID_SINT32;
            format   = "%x";
            break;
        case TOK_DEC_NUMBER:
            bjson_id = MJSON_ID_SINT32;
            format   = "%d";
            break;
        case TOK_FLOAT_NUMBER:
            bjson_id = MJSON_ID_FLOAT32;
            format   = "%f";
            break;
        default:
            assert(!"unknown token");
    }

    bdata = (mjson_entry_t*)parsectx_allocate_output(context, (ptrdiff_t)sizeof(mjson_entry_t));

    if (!bdata) return 0;

    bdata->id = bjson_id;
    num_parsed = sscanf((char*)context->start, format, &bdata->val_u32);
    assert(num_parsed == 1);

    parsectx_next_token(context);
    return 1;
}

static int parse_string(mjson_parser_t *context, uint32_t id)
{
#define YYREADINPUT(c) (c>=e?0:*c)
#define YYCTYPE        uint8_t
#define YYCURSOR       c
#define YYMARKER       m

    uint8_t* c = context->start+1;
    uint8_t* e = context->next;
    uint8_t* m = NULL;
    uint8_t* s;

    mjson_entry_t* bdata;
    uint32_t       ch = 0;
    uint8_t*       str_dst;
    const uint8_t* str_src;
    ptrdiff_t      str_len;
    size_t         len;
    int            num_parsed;

    assert(
        context->token == TOK_STRING       ||
        context->token == TOK_NOESC_STRING ||
        context->token == TOK_IDENTIFIER
    );
    
    bdata = (mjson_entry_t*)parsectx_allocate_output(context, (ptrdiff_t)sizeof(mjson_entry_t));
    
    if (!bdata) return 0;
    
    bdata->id = id;

    if (context->token != TOK_STRING)
    {
        str_src = context->start;
        str_len = context->next - context->start;

        if (context->token==TOK_NOESC_STRING)
        {
            str_src += 1;
            str_len -= 2;
        }
        
        bdata->val_u32 = str_len;

        str_dst = (uint8_t*)parsectx_allocate_output(context, str_len + 1);

        if (!str_dst) return 0;

        memcpy(str_dst, str_src, str_len);
        str_dst[str_len] = 0;

        parsectx_align4_output(context);

        parsectx_next_token(context);

        return 1;
    }

    while (TRUE)
    {
        s = c;


        {
            YYCTYPE yych;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '"') {
                if (yych <= 0x00) goto yy135;
                if (yych >= '"') goto yy133;
            } else {
                if (yych == '\\') goto yy131;
            }
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            goto yy146;
yy130:
            {
                str_dst = (uint8_t*)parsectx_allocate_output(context, c - s);
                
                if (!str_dst) return 0;
                
                memcpy(str_dst, s, c - s);

                continue;
            }
yy131:
            ++YYCURSOR;
            YYMARKER = YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= 'e') {
                if (yych <= '/') {
                    if (yych == '"') goto yy138;
                    if (yych >= '/') goto yy138;
                } else {
                    if (yych <= '\\') {
                        if (yych >= '\\') goto yy138;
                    } else {
                        if (yych == 'b') goto yy138;
                    }
                }
            } else {
                if (yych <= 'q') {
                    if (yych <= 'f') goto yy138;
                    if (yych == 'n') goto yy138;
                } else {
                    if (yych <= 's') {
                        if (yych <= 'r') goto yy138;
                    } else {
                        if (yych <= 't') goto yy138;
                        if (yych <= 'u') goto yy136;
                    }
                }
            }
yy132:
            { 
                assert(!"reachable");
            }
yy133:
            ++YYCURSOR;
            {
                bdata->val_u32 = context->bjson - (uint8_t*)(bdata + 1);
                *context->bjson++ = 0;
                parsectx_align4_output(context);
                parsectx_next_token(context);

                return 1;
            }
yy135:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            goto yy132;
yy136:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '@') {
                if (yych <= '/') goto yy137;
                if (yych <= '9') goto yy140;
            } else {
                if (yych <= 'F') goto yy140;
                if (yych <= '`') goto yy137;
                if (yych <= 'f') goto yy140;
            }
yy137:
            YYCURSOR = YYMARKER;
            goto yy132;
yy138:
            ++YYCURSOR;
            {
                char decoded = s[1];
                
                switch (s[1])
                {
                    case 'b':
                        decoded = '\b';
                        break;
                    case 'n':
                        decoded = '\n';
                        break;
                    case 'r':
                        decoded = '\r';
                        break;
                    case 't':
                        decoded = '\t';
                        break;
                    case 'f':
                        decoded = '\f';
                        break;
                }
                
                str_dst = (uint8_t*)parsectx_allocate_output(context, 1);
                
                if (!str_dst) return 0;
                
                *str_dst = decoded;
                
                continue;
            }
yy140:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '@') {
                if (yych <= '/') goto yy137;
                if (yych >= ':') goto yy137;
            } else {
                if (yych <= 'F') goto yy141;
                if (yych <= '`') goto yy137;
                if (yych >= 'g') goto yy137;
            }
yy141:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '@') {
                if (yych <= '/') goto yy137;
                if (yych >= ':') goto yy137;
            } else {
                if (yych <= 'F') goto yy142;
                if (yych <= '`') goto yy137;
                if (yych >= 'g') goto yy137;
            }
yy142:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
            if (yych <= '@') {
                if (yych <= '/') goto yy137;
                if (yych >= ':') goto yy137;
            } else {
                if (yych <= 'F') goto yy143;
                if (yych <= '`') goto yy137;
                if (yych >= 'g') goto yy137;
            }
yy143:
            ++YYCURSOR;
            {
                str_dst = (uint8_t*)parsectx_reserve_output(context, 6);

                if (!str_dst) return 0;

                num_parsed = sscanf((char*)(s + 2), "%4x", &ch);
                assert(num_parsed == 1);
                unicode_cp_to_utf8(ch, str_dst, &len);

                parsectx_advance_output(context, len);

                continue;
            }
yy145:
            ++YYCURSOR;
            yych = YYREADINPUT(YYCURSOR);
yy146:
            if (yych <= '"') {
                if (yych <= 0x00) goto yy130;
                if (yych <= '!') goto yy145;
                goto yy130;
            } else {
                if (yych == '\\') goto yy130;
                goto yy145;
            }
        }

    }

#undef YYREADINPUT
#undef YYCTYPE           
#undef YYCURSOR          
#undef YYMARKER 

    assert(!"reachable");
    return 0;
}

static int parse_simple(mjson_parser_t *context)
{
    uint32_t* id;

    assert(
        context->token == TOK_NULL  ||
        context->token == TOK_FALSE ||
        context->token == TOK_TRUE
    );

    id = (uint32_t*)parsectx_allocate_output(context, sizeof(uint32_t));
    if (!id) return 0;

    switch (context->token)
    {
        case TOK_NULL:
            *id = MJSON_ID_NULL;
            break;
        case TOK_FALSE:
            *id = MJSON_ID_FALSE;
            break;
        case TOK_TRUE:
            *id = MJSON_ID_TRUE;
            break;
    }

    parsectx_next_token(context);
    return 1;
}

static int parse_value(mjson_parser_t *context)
{
    assert(context);
 
    switch (context->token)
    {
        case TOK_NULL:
        case TOK_FALSE:
        case TOK_TRUE:
            return parse_simple(context);

        case TOK_OCT_NUMBER:
        case TOK_HEX_NUMBER:
        case TOK_DEC_NUMBER:
        case TOK_FLOAT_NUMBER:
            return parse_number(context);

        case TOK_NOESC_STRING:
        case TOK_STRING:
            return parse_string(context, MJSON_ID_UTF8_STRING32);

        case TOK_LEFT_CURLY_BRACKET:
            parsectx_next_token(context);
            return parse_key_value_pair(context, TOK_RIGHT_CURLY_BRACKET);

        case TOK_LEFT_BRACKET:
            parsectx_next_token(context);
            return parse_value_list(context);
    }

    return 0;
}

static int parse_value_list(mjson_parser_t *context)
{
    mjson_entry_t* array;
    uint8_t*       data_start;
    int            expect_separator;

    assert(context);

    array = (mjson_entry_t*)parsectx_allocate_output(context, sizeof(mjson_entry_t));

    if (!array) return 0;
    
    array->id  = MJSON_ID_ARRAY32;
    data_start = context->bjson;

    expect_separator = FALSE;

    while (context->token != TOK_RIGHT_BRACKET)
    {
        if (expect_separator && context->token == TOK_COMMA)
            parsectx_next_token(context);
        else
            expect_separator = TRUE;

        if (!parse_value(context))
            return 0;
    }

    array->val_u32 = context->bjson - data_start;

    assert((array->val_u32 & 3) == 0);

    parsectx_next_token(context);

    return 1;
}

static int parse_key_value_pair(mjson_parser_t* context, int stop_token)
{
    mjson_entry_t* dictionary;
    uint8_t*       data_start;
    int            expect_separator;
 
    assert(context);

    dictionary = (mjson_entry_t*)parsectx_allocate_output(context, sizeof(mjson_entry_t));
    
    if (!dictionary) return 0;
    
    dictionary->id = MJSON_ID_DICT32;
    data_start     = context->bjson;
    
    expect_separator = FALSE;
    while (context->token != stop_token)
    {
        if (expect_separator && context->token == TOK_COMMA)
            parsectx_next_token(context);
        else
            expect_separator = TRUE;

        switch (context->token)
        {
            case TOK_IDENTIFIER:
            case TOK_NOESC_STRING:
                if (!parse_string(context, MJSON_ID_UTF8_KEY32))
                    return 0;
                break;        
            default:
                return 0;
        }

        if (context->token != TOK_COLON && context->token != TOK_EQUAL)
            return 0;

        parsectx_next_token(context);

        if (!parse_value(context))
            return 0;
    }

    dictionary->val_u32 = context->bjson - data_start;
    
    assert((dictionary->val_u32 & 3) == 0);
    
    parsectx_next_token(context);

    return 1;
}
